# Generated by Django 2.1.7 on 2019-05-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('third_party_sh_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('request_mode', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('third_userid', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('userid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('balance', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('transaction_type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('linked_trans_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('expiration_time', models.DateTimeField()),
                ('points_accumulate_so_far', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('member_ship_no', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('token', models.TextField(blank=True, default='', max_length=256, null=True)),
                ('reward_point', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('member_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('expiration_date', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('remaining_balance', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('points_to_be_expire_by_monthend', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('stays_balance', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('nights_balance', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('points_balance', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('point_accumulated', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('nights_accumulated', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('member_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('updated_at', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('cnounce', models.TextField(blank=True, default='', max_length=256, null=True)),
                ('api_timestamp', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'db_table': 'points',
                'managed': False,
            },
        ),
    ]
