# Generated by Django 2.1.7 on 2019-07-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_key', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('requestor_org_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('requestor_id', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'db_table': 'api_key',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('redeemed', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('validated', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('activated', models.CharField(blank=True, default='', max_length=10, null=True)),
            ],
            options={
                'db_table': 'coupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CouponRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_type_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('coupon_count', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('coupon_code', models.TextField(blank=True, default='', null=True)),
                ('coupon_purpose', models.TextField(blank=True, default='', null=True)),
                ('coupon_description', models.TextField(blank=True, default='', null=True)),
                ('coupon_issuance_date', models.DateTimeField()),
                ('coupon_expiration_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'coupon_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CouponType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('prefix_description', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('suffix_description', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('coupon_cost', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('coupon_value', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('coupon_validity_days', models.IntegerField(default=0, null=True)),
                ('coupon_reseller_list_price', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('coupon_currency', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'db_table': 'coupon_type',
                'managed': False,
            },
        ),
    ]
