# Generated by Django 2.1.7 on 2019-05-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('third_userid', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('third_password', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('third_registered_phone_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('third_party_sh_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('request_mode', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('expiration_time', models.DateTimeField()),
                ('error_msg', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('token', models.TextField(blank=True, default='', max_length=256, null=True)),
                ('success', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('cnounce', models.TextField(blank=True, default='', max_length=256, null=True)),
                ('api_timestamp', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': False,
            },
        ),
    ]
