# Generated by Django 2.1.7 on 2019-05-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyNotify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('shopName', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('goodsName', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('couponCode', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('buyAmount', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('buyTime', models.DateTimeField()),
                ('belongArea', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('result', models.TextField(blank=True, default='', max_length=250, null=True)),
                ('cnounce', models.TextField(blank=True, default='', max_length=256, null=True)),
                ('api_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'buynotify',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UseNotify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('shopName', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('goodsName', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('couponCode', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('buyAmount', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('buyTime', models.DateTimeField()),
                ('useStore', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('useAmount', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('useTime', models.DateTimeField()),
                ('belongArea', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('result', models.TextField(blank=True, default='', max_length=250, null=True)),
                ('cnounce', models.TextField(blank=True, default='', max_length=256, null=True)),
                ('api_timestamp', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'db_table': 'usenotify',
                'managed': False,
            },
        ),
    ]
