# Generated by Django 2.1.7 on 2019-06-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_api', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('requested_time', models.DateTimeField()),
                ('ip_address', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'db_table': 'healthcheck',
                'managed': False,
            },
        ),
    ]
